// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Billing Information.
public struct BillingInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. When the billing starts.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. When the billing ends.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  public var currentBillingInfo: OneOf_CurrentBillingInfo? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BillingInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BillingInfo().with { $0.userCountBilling = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let userCountBilling = CodingKeys(stringValue: "userCountBilling")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")

    static let _knownKeys: Set<Swift.String> = [
      "userCountBilling",
      "startTime",
      "endTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)

    var currentBillingInfo: OneOf_CurrentBillingInfo? = nil
    let currentBillingInfoCheckAndSet = {
      if currentBillingInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'currentBillingInfo'"))
      }
      currentBillingInfo = $0
    }
    if let userCountBilling = try container.decodeIfPresent(
      UserCountBillingInfo?.self, forKey: .userCountBilling)
    {
      try currentBillingInfoCheckAndSet(.userCountBilling(userCountBilling))
    }
    self.currentBillingInfo = currentBillingInfo
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)

    if let choice = self.currentBillingInfo {
      switch choice {
      case .userCountBilling(let value):
        try container.encode(value, forKey: .userCountBilling)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_CurrentBillingInfo: Codable, Equatable, Sendable {
    /// Required. This type of billing uses user count for computing total
    /// charge.
    indirect case userCountBilling(UserCountBillingInfo?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.licensemanager.v1.BillingInfo"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
