// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message describing Instance object
public struct Instance: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. name of resource
  public var name: Swift.String = Swift.String()

  /// Output only. [Output only] Create time stamp
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. [Output only] Update time stamp
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Labels as key value pairs
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The state of the VM.
  public var state: Instance.State = Instance.State()

  /// Output only. The location of the VM.
  public var region: Swift.String = Swift.String()

  /// Output only. Map with Product_Name and Activation State of the VM.
  public var productActivation: [Swift.String: ActivationState] = [:]

  /// Output only. license version id.
  public var licenseVersionId: Swift.String = Swift.String()

  /// Required. Compute Instance resource name, i.e.
  /// projects/{project}/zones/{zone}/instances/{instance}
  public var computeInstance: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Instance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Instance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let state = CodingKeys(stringValue: "state")
    static let region = CodingKeys(stringValue: "region")
    static let productActivation = CodingKeys(stringValue: "productActivation")
    static let licenseVersionId = CodingKeys(stringValue: "licenseVersionId")
    static let computeInstance = CodingKeys(stringValue: "computeInstance")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "state",
      "region",
      "productActivation",
      "licenseVersionId",
      "computeInstance",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Instance.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .region) {
      self.region = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: ActivationState].self, forKey: .productActivation)
    {
      self.productActivation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .licenseVersionId) {
      self.licenseVersionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .computeInstance) {
      self.computeInstance = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.region, forKey: .region)
    try container.encode(self.productActivation, forKey: .productActivation)
    try container.encode(self.licenseVersionId, forKey: .licenseVersionId)
    try container.encode(self.computeInstance, forKey: .computeInstance)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// VM status enum.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The Status of the VM is unspecified.
    case unspecified
    /// Resources are being allocated for the instance.
    case provisioning
    /// All required resources have been allocated and
    /// the instance is being started.
    case staging
    /// The instance is running.
    case running
    /// The instance is currently stopping (either being deleted or terminated).
    case stopping
    /// The instance has stopped due to various reasons (user request, VM
    /// preemption, project freezing, etc.).
    case stopped
    /// The instance has failed in some way.
    case terminated
    /// The instance is in repair.
    case repairing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .staging: return 2
      case .running: return 3
      case .stopping: return 4
      case .stopped: return 5
      case .terminated: return 6
      case .repairing: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .staging: return "STAGING"
      case .running: return "RUNNING"
      case .stopping: return "STOPPING"
      case .stopped: return "STOPPED"
      case .terminated: return "TERMINATED"
      case .repairing: return "REPAIRING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "STAGING": self = .staging
      case "RUNNING": self = .running
      case "STOPPING": self = .stopping
      case "STOPPED": self = .stopped
      case "TERMINATED": self = .terminated
      case "REPAIRING": self = .repairing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .staging
      case 3: self = .running
      case 4: self = .stopping
      case 5: self = .stopped
      case 6: self = .terminated
      case 7: self = .repairing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .provisioning: return try container.encode("PROVISIONING")
      case .staging: return try container.encode("STAGING")
      case .running: return try container.encode("RUNNING")
      case .stopping: return try container.encode("STOPPING")
      case .stopped: return try container.encode("STOPPED")
      case .terminated: return try container.encode("TERMINATED")
      case .repairing: return try container.encode("REPAIRING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.licensemanager.v1.Instance"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
