// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "LicenseManagerQuickstart")
public final class LicenseManagerClient: Clients.LicenseManagerProtocol, Sendable {
  let inner: any Clients.LicenseManagerStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `LicenseManagerClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.LicenseManagerStub = try Clients.LicenseManagerTransport(options)
    inner = Clients.LicenseManagerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.LicenseManagerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Configurations in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListConfigurations")
  public func listConfigurations(
    request: ListConfigurationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse {
    try await self.inner.listConfigurations(request: request, options: options)
  }

  /// Gets details of a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_GetConfiguration")
  public func getConfiguration(
    request: GetConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
    try await self.inner.getConfiguration(request: request, options: options)
  }

  /// Creates a new Configuration in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_CreateConfiguration")
  public func createConfiguration(
    request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConfiguration(request: request, options: options)
  }

  /// Creates a new Configuration in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_CreateConfiguration")
  public func createConfigurationPollingUntilDone(
    request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.createConfiguration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the parameters of a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_UpdateConfiguration")
  public func updateConfiguration(
    request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConfiguration(request: request, options: options)
  }

  /// Updates the parameters of a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_UpdateConfiguration")
  public func updateConfigurationPollingUntilDone(
    request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.updateConfiguration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeleteConfiguration")
  public func deleteConfiguration(
    request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConfiguration(request: request, options: options)
  }

  /// Deletes a single Configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeleteConfiguration")
  public func deleteConfigurationPollingUntilDone(
    request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConfiguration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListInstances")
  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse {
    try await self.inner.listInstances(request: request, options: options)
  }

  /// Gets details of a single Instance.
  ///
  /// @Snippet(path: "LicenseManager_GetInstance")
  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Instance {
    try await self.inner.getInstance(request: request, options: options)
  }

  /// Deactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeactivateConfiguration")
  public func deactivateConfiguration(
    request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deactivateConfiguration(request: request, options: options)
  }

  /// Deactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_DeactivateConfiguration")
  public func deactivateConfigurationPollingUntilDone(
    request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.deactivateConfiguration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Reactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_ReactivateConfiguration")
  public func reactivateConfiguration(
    request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.reactivateConfiguration(request: request, options: options)
  }

  /// Reactivates the given configuration.
  ///
  /// @Snippet(path: "LicenseManager_ReactivateConfiguration")
  public func reactivateConfigurationPollingUntilDone(
    request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Configuration>.State in
      return try op._extractStatus(Configuration.self)
    }
    let rawOp = try await self.reactivateConfiguration(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// License Usage information for a Configuration.
  ///
  /// @Snippet(path: "LicenseManager_QueryConfigurationLicenseUsage")
  public func queryConfigurationLicenseUsage(
    request: QueryConfigurationLicenseUsageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
    try await self.inner.queryConfigurationLicenseUsage(request: request, options: options)
  }

  /// Aggregates Usage per Instance for a Configuration.
  ///
  /// @Snippet(path: "LicenseManager_AggregateUsage")
  public func aggregateUsage(
    request: AggregateUsageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse {
    try await self.inner.aggregateUsage(request: request, options: options)
  }

  /// Lists Products in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListProducts")
  public func listProducts(
    request: ListProductsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse {
    try await self.inner.listProducts(request: request, options: options)
  }

  /// Gets details of a single Product.
  ///
  /// @Snippet(path: "LicenseManager_GetProduct")
  public func getProduct(
    request: GetProductRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Product {
    try await self.inner.getProduct(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "LicenseManager_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "LicenseManager_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `LicenseManagerClient`.
  ///
  /// To mock `LicenseManagerClient` change your functions to receive
  /// `some LicenseManagerProtocol` or `any LicenseManagerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol LicenseManagerProtocol: Sendable {
    /// See `LicenseManagerClient.listConfigurations`.
    func listConfigurations(
      request: ListConfigurationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse

    /// See `LicenseManagerClient.getConfiguration`.
    func getConfiguration(
      request: GetConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Configuration

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfiguration(
      request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.createConfiguration`.
    func createConfigurationPollingUntilDone(
      request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfiguration(
      request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.updateConfiguration`.
    func updateConfigurationPollingUntilDone(
      request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfiguration(
      request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.deleteConfiguration`.
    func deleteConfigurationPollingUntilDone(
      request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `LicenseManagerClient.listInstances`.
    func listInstances(
      request: ListInstancesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse

    /// See `LicenseManagerClient.getInstance`.
    func getInstance(
      request: GetInstanceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Instance

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfiguration(
      request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.deactivateConfiguration`.
    func deactivateConfigurationPollingUntilDone(
      request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfiguration(
      request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `LicenseManagerClient.reactivateConfiguration`.
    func reactivateConfigurationPollingUntilDone(
      request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Configuration>

    /// See `LicenseManagerClient.queryConfigurationLicenseUsage`.
    func queryConfigurationLicenseUsage(
      request: QueryConfigurationLicenseUsageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse

    /// See `LicenseManagerClient.aggregateUsage`.
    func aggregateUsage(
      request: AggregateUsageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse

    /// See `LicenseManagerClient.listProducts`.
    func listProducts(
      request: ListProductsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse

    /// See `LicenseManagerClient.getProduct`.
    func getProduct(
      request: GetProductRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLicenseManagerV1.Product

    /// See `LicenseManagerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `LicenseManagerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `LicenseManagerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `LicenseManagerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `LicenseManagerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.LicenseManagerProtocol {
  public func listConfigurations(request: ListConfigurationsRequest) async throws
    -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse
  {
    try await self.listConfigurations(request: request, options: .init())
  }

  public func listConfigurations(
    request: ListConfigurationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConfigurationsByItems(
    request: ListConfigurationsRequest
  ) -> any AsyncSequence<Configuration, Swift.Error> & Sendable {
    self.listConfigurationsByItems(request: request, options: .init())
  }

  /// Lists Configurations in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListConfigurations")
  public func listConfigurationsByItems(
    request: ListConfigurationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Configuration, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudLicenseManagerV1.ListConfigurationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listConfigurations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConfigurationsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Configuration, Swift.Error> & Sendable {
    let request = ListConfigurationsRequest().with {
      $0.parent = parent
    }
    return self.listConfigurationsByItems(request: request)
  }

  public func getConfiguration(request: GetConfigurationRequest) async throws
    -> GoogleCloudLicenseManagerV1.Configuration
  {
    try await self.getConfiguration(request: request, options: .init())
  }

  public func getConfiguration(
    request: GetConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConfiguration(
    name: Swift.String,
  ) async throws -> GoogleCloudLicenseManagerV1.Configuration {
    let request = GetConfigurationRequest().with {
      $0.name = name
    }
    return try await self.getConfiguration(request: request)
  }

  public func createConfiguration(request: CreateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConfiguration(request: request, options: .init())
  }

  public func createConfiguration(
    request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createConfigurationPollingUntilDone(request: CreateConfigurationRequest) async throws
    -> any GoogleGax.PollableOperation<Configuration>
  {
    try await self.createConfigurationPollingUntilDone(request: request, options: .init())
  }

  public func createConfigurationPollingUntilDone(
    request: CreateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConfigurationPollingUntilDone(
    parent: Swift.String,
    configuration: Configuration?,
    configurationId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let request = CreateConfigurationRequest().with {
      $0.parent = parent
      $0.configuration = configuration
      $0.configurationId = configurationId
    }
    return try await self.createConfigurationPollingUntilDone(request: request)
  }

  public func updateConfiguration(request: UpdateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConfiguration(request: request, options: .init())
  }

  public func updateConfiguration(
    request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConfigurationPollingUntilDone(request: UpdateConfigurationRequest) async throws
    -> any GoogleGax.PollableOperation<Configuration>
  {
    try await self.updateConfigurationPollingUntilDone(request: request, options: .init())
  }

  public func updateConfigurationPollingUntilDone(
    request: UpdateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConfigurationPollingUntilDone(
    configuration: Configuration?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let request = UpdateConfigurationRequest().with {
      $0.configuration = configuration
      $0.updateMask = updateMask
    }
    return try await self.updateConfigurationPollingUntilDone(request: request)
  }

  public func deleteConfiguration(request: DeleteConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConfiguration(request: request, options: .init())
  }

  public func deleteConfiguration(
    request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConfigurationPollingUntilDone(request: DeleteConfigurationRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteConfigurationPollingUntilDone(request: request, options: .init())
  }

  public func deleteConfigurationPollingUntilDone(
    request: DeleteConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConfigurationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteConfigurationRequest().with {
      $0.name = name
    }
    return try await self.deleteConfigurationPollingUntilDone(request: request)
  }

  public func listInstances(request: ListInstancesRequest) async throws
    -> GoogleCloudLicenseManagerV1.ListInstancesResponse
  {
    try await self.listInstances(request: request, options: .init())
  }

  public func listInstances(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListInstancesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listInstancesByItems(
    request: ListInstancesRequest
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    self.listInstancesByItems(request: request, options: .init())
  }

  /// Lists Instances in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListInstances")
  public func listInstancesByItems(
    request: ListInstancesRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudLicenseManagerV1.ListInstancesResponse in
      var request = request
      request.pageToken = token
      return try await self.listInstances(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listInstancesByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Instance, Swift.Error> & Sendable {
    let request = ListInstancesRequest().with {
      $0.parent = parent
    }
    return self.listInstancesByItems(request: request)
  }

  public func getInstance(request: GetInstanceRequest) async throws
    -> GoogleCloudLicenseManagerV1.Instance
  {
    try await self.getInstance(request: request, options: .init())
  }

  public func getInstance(
    request: GetInstanceRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Instance {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getInstance(
    name: Swift.String,
  ) async throws -> GoogleCloudLicenseManagerV1.Instance {
    let request = GetInstanceRequest().with {
      $0.name = name
    }
    return try await self.getInstance(request: request)
  }

  public func deactivateConfiguration(request: DeactivateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deactivateConfiguration(request: request, options: .init())
  }

  public func deactivateConfiguration(
    request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deactivateConfigurationPollingUntilDone(request: DeactivateConfigurationRequest)
    async throws -> any GoogleGax.PollableOperation<Configuration>
  {
    try await self.deactivateConfigurationPollingUntilDone(request: request, options: .init())
  }

  public func deactivateConfigurationPollingUntilDone(
    request: DeactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deactivateConfigurationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let request = DeactivateConfigurationRequest().with {
      $0.name = name
    }
    return try await self.deactivateConfigurationPollingUntilDone(request: request)
  }

  public func reactivateConfiguration(request: ReactivateConfigurationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.reactivateConfiguration(request: request, options: .init())
  }

  public func reactivateConfiguration(
    request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func reactivateConfigurationPollingUntilDone(request: ReactivateConfigurationRequest)
    async throws -> any GoogleGax.PollableOperation<Configuration>
  {
    try await self.reactivateConfigurationPollingUntilDone(request: request, options: .init())
  }

  public func reactivateConfigurationPollingUntilDone(
    request: ReactivateConfigurationRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<Configuration>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func reactivateConfigurationPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Configuration> {
    let request = ReactivateConfigurationRequest().with {
      $0.name = name
    }
    return try await self.reactivateConfigurationPollingUntilDone(request: request)
  }

  public func queryConfigurationLicenseUsage(request: QueryConfigurationLicenseUsageRequest)
    async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse
  {
    try await self.queryConfigurationLicenseUsage(request: request, options: .init())
  }

  public func queryConfigurationLicenseUsage(
    request: QueryConfigurationLicenseUsageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func queryConfigurationLicenseUsage(
    name: Swift.String,
    startTime: GoogleWKT.WKTTimestamp?,
    endTime: GoogleWKT.WKTTimestamp?,
  ) async throws -> GoogleCloudLicenseManagerV1.QueryConfigurationLicenseUsageResponse {
    let request = QueryConfigurationLicenseUsageRequest().with {
      $0.name = name
      $0.startTime = startTime
      $0.endTime = endTime
    }
    return try await self.queryConfigurationLicenseUsage(request: request)
  }

  public func aggregateUsage(request: AggregateUsageRequest) async throws
    -> GoogleCloudLicenseManagerV1.AggregateUsageResponse
  {
    try await self.aggregateUsage(request: request, options: .init())
  }

  public func aggregateUsage(
    request: AggregateUsageRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.AggregateUsageResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func aggregateUsageByItems(
    request: AggregateUsageRequest
  ) -> any AsyncSequence<Usage, Swift.Error> & Sendable {
    self.aggregateUsageByItems(request: request, options: .init())
  }

  /// Aggregates Usage per Instance for a Configuration.
  ///
  /// @Snippet(path: "LicenseManager_AggregateUsage")
  public func aggregateUsageByItems(
    request: AggregateUsageRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Usage, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudLicenseManagerV1.AggregateUsageResponse in
      var request = request
      request.pageToken = token
      return try await self.aggregateUsage(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func aggregateUsageByItems(
    name: Swift.String,
    startTime: GoogleWKT.WKTTimestamp?,
    endTime: GoogleWKT.WKTTimestamp?,
  ) -> any AsyncSequence<Usage, Swift.Error> & Sendable {
    let request = AggregateUsageRequest().with {
      $0.name = name
      $0.startTime = startTime
      $0.endTime = endTime
    }
    return self.aggregateUsageByItems(request: request)
  }

  public func listProducts(request: ListProductsRequest) async throws
    -> GoogleCloudLicenseManagerV1.ListProductsResponse
  {
    try await self.listProducts(request: request, options: .init())
  }

  public func listProducts(
    request: ListProductsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.ListProductsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listProductsByItems(
    request: ListProductsRequest
  ) -> any AsyncSequence<Product, Swift.Error> & Sendable {
    self.listProductsByItems(request: request, options: .init())
  }

  /// Lists Products in a given project and location.
  ///
  /// @Snippet(path: "LicenseManager_ListProducts")
  public func listProductsByItems(
    request: ListProductsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<Product, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudLicenseManagerV1.ListProductsResponse in
      var request = request
      request.pageToken = token
      return try await self.listProducts(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProductsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<Product, Swift.Error> & Sendable {
    let request = ListProductsRequest().with {
      $0.parent = parent
    }
    return self.listProductsByItems(request: request)
  }

  public func getProduct(request: GetProductRequest) async throws
    -> GoogleCloudLicenseManagerV1.Product
  {
    try await self.getProduct(request: request, options: .init())
  }

  public func getProduct(
    request: GetProductRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLicenseManagerV1.Product {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getProduct(
    name: Swift.String,
  ) async throws -> GoogleCloudLicenseManagerV1.Product {
    let request = GetProductRequest().with {
      $0.name = name
    }
    return try await self.getProduct(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "LicenseManager_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "LicenseManager_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
