// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Message for response to get the license usage per configuration.
public struct QueryConfigurationLicenseUsageResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Depending on the type of the configuration, one of the following
  /// will be populated.
  public var details: DetailsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QueryConfigurationLicenseUsageResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryConfigurationLicenseUsageResponse().with { $0.userCountUsage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let userCountUsage = CodingKeys(stringValue: "userCountUsage")

    static let _knownKeys: Set<Swift.String> = [
      "userCountUsage"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var details: DetailsOneOf? = nil
    let detailsCheckAndSet = {
      if details != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'details'"))
      }
      details = $0
    }
    if let userCountUsage = try container.decodeIfPresent(
      UserCountUsage.self, forKey: .userCountUsage)
    {
      try detailsCheckAndSet(.userCountUsage(userCountUsage))
    }
    self.details = details
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.details {
      switch choice {
      case .userCountUsage(let value):
        try container.encode(value, forKey: .userCountUsage)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Depending on the type of the configuration, one of the following
  /// will be populated.
  public enum DetailsOneOf: Codable, Equatable, Sendable {
    /// Usage information for license types which use user-count billing.
    indirect case userCountUsage(UserCountUsage)
  }

  /// The type URL for `QueryConfigurationLicenseUsageResponse`: `"type.googleapis.com/google.cloud.licensemanager.v1.QueryConfigurationLicenseUsageResponse"`.
  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.licensemanager.v1.QueryConfigurationLicenseUsageResponse"
  }

  /// Initialize an instance of `QueryConfigurationLicenseUsageResponse` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.licensemanager.v1.QueryConfigurationLicenseUsageResponse"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `QueryConfigurationLicenseUsageResponse` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
